### PR TITLE
Doc mengzhu

### PR DESCRIPTION
**Pull request by mengzhuwang**
Introduction part and GUI implementation

### CODE REVIEW

**Comment by iroq** [comment]
You removed the `.gitignore` file, which makes Git ignore all the LaTeX compilation files so we don't accidentally commit them. Can you bring it back?

**Comment by mengzhuwang** [comment]
I bring it back. @iroq

**Comment by iroq** [comment]
It doesn't compile, you didn't include your `.eps` files.

**Comment by mengzhuwang** [comment]
add pictures @iroq

**Pull request merged**
