### PR TITLE
Feat junctiondug 75

### PR DESCRIPTION
**Pull request by mengzhuwang**
fix vehicles turning problem on junctions

### CODE REVIEW

**Comment by iroq** [comment]
waiting for merge of #69

**Comment by mengzhuwang** [comment]
do you mean I can merge this branch with 69 right now? @iroq

**Comment by iroq** [comment]
no no, I'm waiting for @vezer1993 to merge pull request #69 first because this pull request builds on things from #69

**Comment by mengzhuwang** [comment]
ok, got it

**Pull request merged**
